title: Robotic Manipulation Notebook
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://lihanlian.github.io
baseurl: "/robotic-manipulation-notebook"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

defaults:
  - scope:
      path: "docs"
    values:
      layout: "default"
